package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.AppMsgTpl;
import com.adpanshi.cashloan.manage.cl.model.AppMsgTplExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface AppMsgTplMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_app_msg_tpl
     *
     * @mbg.generated
     */
    long countByExample(AppMsgTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_app_msg_tpl
     *
     * @mbg.generated
     */
    int deleteByExample(AppMsgTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_app_msg_tpl
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_app_msg_tpl
     *
     * @mbg.generated
     */
    int insert(AppMsgTpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_app_msg_tpl
     *
     * @mbg.generated
     */
    int insertSelective(AppMsgTpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_app_msg_tpl
     *
     * @mbg.generated
     */
    List<AppMsgTpl> selectByExample(AppMsgTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_app_msg_tpl
     *
     * @mbg.generated
     */
    AppMsgTpl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_app_msg_tpl
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AppMsgTpl record, @Param("example") AppMsgTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_app_msg_tpl
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AppMsgTpl record, @Param("example") AppMsgTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_app_msg_tpl
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppMsgTpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_app_msg_tpl
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppMsgTpl record);
}