package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.BankCard;
import com.adpanshi.cashloan.manage.cl.model.BankCardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface BankCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_bank_card
     *
     * @mbg.generated
     */
    long countByExample(BankCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_bank_card
     *
     * @mbg.generated
     */
    int deleteByExample(BankCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_bank_card
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_bank_card
     *
     * @mbg.generated
     */
    int insert(BankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_bank_card
     *
     * @mbg.generated
     */
    int insertSelective(BankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_bank_card
     *
     * @mbg.generated
     */
    List<BankCard> selectByExample(BankCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_bank_card
     *
     * @mbg.generated
     */
    BankCard selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_bank_card
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BankCard record, @Param("example") BankCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_bank_card
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BankCard record, @Param("example") BankCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_bank_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BankCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_bank_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BankCard record);
}