package com.adpanshi.cashloan.manage.cl.mapper;


import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.Borrow;
import com.adpanshi.cashloan.manage.cl.model.BorrowRepay;
import com.adpanshi.cashloan.manage.cl.model.BorrowRepayExample;
import java.util.List;
import java.util.Map;

import com.adpanshi.cashloan.manage.cl.model.expand.BorrowModel;
import com.adpanshi.cashloan.manage.cl.model.expand.BorrowRepayModel;
import com.adpanshi.cashloan.manage.cl.pojo.OverDueUser;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface BorrowRepayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay
     *
     * @mbg.generated
     */
    long countByExample(BorrowRepayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay
     *
     * @mbg.generated
     */
    int deleteByExample(BorrowRepayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay
     *
     * @mbg.generated
     */
    int insert(BorrowRepay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay
     *
     * @mbg.generated
     */
    int insertSelective(BorrowRepay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay
     *
     * @mbg.generated
     */
    List<BorrowRepay> selectByExample(BorrowRepayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay
     *
     * @mbg.generated
     */
    BorrowRepay selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BorrowRepay record, @Param("example") BorrowRepayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BorrowRepay record, @Param("example") BorrowRepayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BorrowRepay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BorrowRepay record);
    /**
     *  查询还款计划列表
     * @param params
     * @return List<BorrowRepayModel>
     * @throws
     * @author Vic Tang
     * @date 2018/7/31 21:26
     * */
    List<BorrowRepayModel> listModelNew(Map<String, Object> params);

    /**
     * 逾期未入催
     * @param params
     * @return
     */
    List<BorrowModel> listModelNotUrge(Map<String, Object> params);

    /**
     * 批量保存
     * @param repayList
     * @return
     */
    int saveAll(@Param("list")List<BorrowRepay> repayList);
    /**
     * 后台还款记录列表
     * @param params
     * @return
     */
    List<BorrowRepayModel> listModel(Map<String, Object> params);
    /**
     *  查看还款订单逾期信息
     * @param borrowId
     * @return BorrowRepayModel
     * @throws
     * @author Vic Tang
     * @date 2018/8/6 23:20
     * */
    BorrowRepayModel findOverdue(long borrowId);

    int updateParam(Map<String, Object> paramMap);

    List<BorrowRepay> listSelective(Map<String, Object> paramMap);

    List<OverDueUser> listOverDueUser();
}