package com.adpanshi.cashloan.manage.cl.mapper;


import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.BorrowRepayLog;
import com.adpanshi.cashloan.manage.cl.model.BorrowRepayLogExample;
import java.util.List;
import java.util.Map;

import com.adpanshi.cashloan.manage.cl.model.expand.BorrowRepayLogModel;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface BorrowRepayLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay_log
     *
     * @mbg.generated
     */
    long countByExample(BorrowRepayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay_log
     *
     * @mbg.generated
     */
    int deleteByExample(BorrowRepayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay_log
     *
     * @mbg.generated
     */
    int insert(BorrowRepayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay_log
     *
     * @mbg.generated
     */
    int insertSelective(BorrowRepayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay_log
     *
     * @mbg.generated
     */
    List<BorrowRepayLog> selectByExample(BorrowRepayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay_log
     *
     * @mbg.generated
     */
    BorrowRepayLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BorrowRepayLog record, @Param("example") BorrowRepayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BorrowRepayLog record, @Param("example") BorrowRepayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BorrowRepayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_repay_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BorrowRepayLog record);
    /**
     *  模糊查询还款记录列表
     * @param params
     * @return List<BorrowRepayLogModel>
     * @throws
     * @author Vic Tang
     * @date 2018/8/1 10:43
     * */
    List<BorrowRepayLogModel> listModel(Map<String, Object> params);
    /**
     * @Description: 获取还款信息
     * @Param: [id]
     * @return: java.util.Map
     * @Author: Mr.Wange
     * @Date: 2018/7/25
     */
    Map qryRepayLog(Long id);
}