package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.manage.cl.model.BorrowTemplate;
import com.adpanshi.cashloan.manage.cl.model.BorrowTemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BorrowTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_template
     *
     * @mbg.generated
     */
    long countByExample(BorrowTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_template
     *
     * @mbg.generated
     */
    int deleteByExample(BorrowTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_template
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_template
     *
     * @mbg.generated
     */
    int insert(BorrowTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_template
     *
     * @mbg.generated
     */
    int insertSelective(BorrowTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_template
     *
     * @mbg.generated
     */
    List<BorrowTemplate> selectByExample(BorrowTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_template
     *
     * @mbg.generated
     */
    BorrowTemplate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_template
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BorrowTemplate record, @Param("example") BorrowTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_template
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BorrowTemplate record, @Param("example") BorrowTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BorrowTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BorrowTemplate record);
}