package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.BorrowAuditLog;
import com.adpanshi.cashloan.manage.cl.model.BorrowAuditLogExample;
import com.adpanshi.cashloan.manage.cl.model.BorrowAuditLogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface BorrowAuditLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_audit_log
     *
     * @mbg.generated
     */
    long countByExample(BorrowAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_audit_log
     *
     * @mbg.generated
     */
    int deleteByExample(BorrowAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_audit_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_audit_log
     *
     * @mbg.generated
     */
    int insert(BorrowAuditLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_audit_log
     *
     * @mbg.generated
     */
    int insertSelective(BorrowAuditLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_audit_log
     *
     * @mbg.generated
     */
    List<BorrowAuditLogWithBLOBs> selectByExampleWithBLOBs(BorrowAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_audit_log
     *
     * @mbg.generated
     */
    List<BorrowAuditLog> selectByExample(BorrowAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_audit_log
     *
     * @mbg.generated
     */
    BorrowAuditLogWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_audit_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BorrowAuditLogWithBLOBs record, @Param("example") BorrowAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_audit_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") BorrowAuditLogWithBLOBs record, @Param("example") BorrowAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_audit_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BorrowAuditLog record, @Param("example") BorrowAuditLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_audit_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BorrowAuditLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_audit_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(BorrowAuditLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_audit_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BorrowAuditLog record);
}