package com.adpanshi.cashloan.manage.cl.mapper;


import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.BorrowMain;
import com.adpanshi.cashloan.manage.cl.model.BorrowMainExample;
import java.util.List;
import java.util.Map;

import com.adpanshi.cashloan.manage.cl.model.expand.BorrowMainModel;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface BorrowMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main
     *
     * @mbg.generated
     */
    long countByExample(BorrowMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main
     *
     * @mbg.generated
     */
    int deleteByExample(BorrowMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main
     *
     * @mbg.generated
     */
    int insert(BorrowMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main
     *
     * @mbg.generated
     */
    int insertSelective(BorrowMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main
     *
     * @mbg.generated
     */
    List<BorrowMain> selectByExampleWithBLOBs(BorrowMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main
     *
     * @mbg.generated
     */
    List<BorrowMain> selectByExample(BorrowMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main
     *
     * @mbg.generated
     */
    BorrowMain selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BorrowMain record, @Param("example") BorrowMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") BorrowMain record, @Param("example") BorrowMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BorrowMain record, @Param("example") BorrowMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BorrowMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(BorrowMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BorrowMain record);
    /**
     * 查询所有订单信息 (用户, 用户基本信息)
     * @param searchParams
     * @return List<BorrowMain>
     */
    List<BorrowMainModel> selectBorrowList(Map<String, Object> searchParams);

    /**
     * 查询信审人员订单分配最少的（无关联）
     * @param data
     * @return BorrowMainModel
     */
    BorrowMainModel selectBorrowSysCount(Map<String,Object> data);
    /**
     *  获取主订单扩展信息
     * @param borrowMainId
     * @return BorrowMainModel
     * @throws
     * @author Vic Tang
     * @date 2018/8/6 23:14
     * */
    BorrowMainModel findById(long borrowMainId);
    /**
     * <p>根据brrowId、userId查询主订单</p>
     * @param borrowId
     * @param userId
     * @return
     * */
    BorrowMain getBowMainByBorrowIdWithUserId(@Param("borrowId")Long borrowId, @Param("userId")Long userId);
}