package com.adpanshi.cashloan.manage.cl.mapper;


import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.BorrowMainProgress;
import com.adpanshi.cashloan.manage.cl.model.BorrowMainProgressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface BorrowMainProgressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main_progress
     *
     * @mbg.generated
     */
    long countByExample(BorrowMainProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main_progress
     *
     * @mbg.generated
     */
    int deleteByExample(BorrowMainProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main_progress
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main_progress
     *
     * @mbg.generated
     */
    int insert(BorrowMainProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main_progress
     *
     * @mbg.generated
     */
    int insertSelective(BorrowMainProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main_progress
     *
     * @mbg.generated
     */
    List<BorrowMainProgress> selectByExample(BorrowMainProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main_progress
     *
     * @mbg.generated
     */
    BorrowMainProgress selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main_progress
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BorrowMainProgress record, @Param("example") BorrowMainProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main_progress
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BorrowMainProgress record, @Param("example") BorrowMainProgressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main_progress
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BorrowMainProgress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_borrow_main_progress
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BorrowMainProgress record);
}