package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.Channel;
import com.adpanshi.cashloan.manage.cl.model.ChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface ChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_channel
     *
     * @mbg.generated
     */
    long countByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_channel
     *
     * @mbg.generated
     */
    int deleteByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_channel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_channel
     *
     * @mbg.generated
     */
    int insert(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_channel
     *
     * @mbg.generated
     */
    int insertSelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_channel
     *
     * @mbg.generated
     */
    List<Channel> selectByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_channel
     *
     * @mbg.generated
     */
    Channel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_channel
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Channel record, @Param("example") ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_channel
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Channel record, @Param("example") ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_channel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_channel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Channel record);
    /**
     * 查出所有渠道信息
     */
    List<Channel> listChannel();
}