package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.ExamineDictDetail;
import com.adpanshi.cashloan.manage.cl.model.ExamineDictDetailExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface ExamineDictDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_examine_dict_detail
     *
     * @mbg.generated
     */
    long countByExample(ExamineDictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_examine_dict_detail
     *
     * @mbg.generated
     */
    int deleteByExample(ExamineDictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_examine_dict_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_examine_dict_detail
     *
     * @mbg.generated
     */
    int insert(ExamineDictDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_examine_dict_detail
     *
     * @mbg.generated
     */
    int insertSelective(ExamineDictDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_examine_dict_detail
     *
     * @mbg.generated
     */
    List<ExamineDictDetail> selectByExample(ExamineDictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_examine_dict_detail
     *
     * @mbg.generated
     */
    ExamineDictDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_examine_dict_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ExamineDictDetail record, @Param("example") ExamineDictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_examine_dict_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ExamineDictDetail record, @Param("example") ExamineDictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_examine_dict_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExamineDictDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_examine_dict_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExamineDictDetail record);
    /**
     * 查询字段的所有信息
     * @param params
     * @return
     */
    List<ExamineDictDetail>  findExamineDictDetailInfo(Map<String, Object> params);
    /**
     * 查询最大的code值
     */
    Long selectMaxCode();

}