package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.Notices;
import com.adpanshi.cashloan.manage.cl.model.NoticesExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;
import org.apache.poi.ss.formula.functions.T;

@RDBatisDao
public interface NoticesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_notices
     *
     * @mbg.generated
     */
    long countByExample(NoticesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_notices
     *
     * @mbg.generated
     */
    int deleteByExample(NoticesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_notices
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_notices
     *
     * @mbg.generated
     */
    int insert(Notices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_notices
     *
     * @mbg.generated
     */
    int insertSelective(Notices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_notices
     *
     * @mbg.generated
     */
    List<Notices> selectByExample(NoticesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_notices
     *
     * @mbg.generated
     */
    Notices selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_notices
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Notices record, @Param("example") NoticesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_notices
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Notices record, @Param("example") NoticesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_notices
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Notices record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_notices
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Notices record);

    /**
     * 数据查询
     *
     * @param paramMap
     *            查询条件
     * @return 结果集
     */
    List<Notices> listSelective(Map<String, Object> paramMap);
}