package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.OverduePhone;
import com.adpanshi.cashloan.manage.cl.model.OverduePhoneExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface OverduePhoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_overdue_phone
     *
     * @mbg.generated
     */
    long countByExample(OverduePhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_overdue_phone
     *
     * @mbg.generated
     */
    int deleteByExample(OverduePhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_overdue_phone
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_overdue_phone
     *
     * @mbg.generated
     */
    int insert(OverduePhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_overdue_phone
     *
     * @mbg.generated
     */
    int insertSelective(OverduePhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_overdue_phone
     *
     * @mbg.generated
     */
    List<OverduePhone> selectByExample(OverduePhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_overdue_phone
     *
     * @mbg.generated
     */
    OverduePhone selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_overdue_phone
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OverduePhone record, @Param("example") OverduePhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_overdue_phone
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OverduePhone record, @Param("example") OverduePhoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_overdue_phone
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OverduePhone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_overdue_phone
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OverduePhone record);

    List<OverduePhone> listByCondition(Map<String, Object> paramMap);

    int deleteByIds(List<Long> ids);
}