package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.PayCheck;
import com.adpanshi.cashloan.manage.cl.model.PayCheckExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface PayCheckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_check
     *
     * @mbg.generated
     */
    long countByExample(PayCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_check
     *
     * @mbg.generated
     */
    int deleteByExample(PayCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_check
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_check
     *
     * @mbg.generated
     */
    int insert(PayCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_check
     *
     * @mbg.generated
     */
    int insertSelective(PayCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_check
     *
     * @mbg.generated
     */
    List<PayCheck> selectByExample(PayCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_check
     *
     * @mbg.generated
     */
    PayCheck selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_check
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PayCheck record, @Param("example") PayCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_check
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PayCheck record, @Param("example") PayCheckExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_check
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayCheck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_check
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayCheck record);
}