package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.PayReqLog;
import com.adpanshi.cashloan.manage.cl.model.PayReqLogExample;
import com.adpanshi.cashloan.manage.cl.model.PayReqLogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface PayReqLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_req_log
     *
     * @mbg.generated
     */
    long countByExample(PayReqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_req_log
     *
     * @mbg.generated
     */
    int deleteByExample(PayReqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_req_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_req_log
     *
     * @mbg.generated
     */
    int insert(PayReqLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_req_log
     *
     * @mbg.generated
     */
    int insertSelective(PayReqLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_req_log
     *
     * @mbg.generated
     */
    List<PayReqLogWithBLOBs> selectByExampleWithBLOBs(PayReqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_req_log
     *
     * @mbg.generated
     */
    List<PayReqLog> selectByExample(PayReqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_req_log
     *
     * @mbg.generated
     */
    PayReqLogWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_req_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PayReqLogWithBLOBs record, @Param("example") PayReqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_req_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PayReqLogWithBLOBs record, @Param("example") PayReqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_req_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PayReqLog record, @Param("example") PayReqLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_req_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayReqLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_req_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PayReqLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_req_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayReqLog record);
}