package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.PayRespLog;
import com.adpanshi.cashloan.manage.cl.model.PayRespLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface PayRespLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_resp_log
     *
     * @mbg.generated
     */
    long countByExample(PayRespLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_resp_log
     *
     * @mbg.generated
     */
    int deleteByExample(PayRespLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_resp_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_resp_log
     *
     * @mbg.generated
     */
    int insert(PayRespLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_resp_log
     *
     * @mbg.generated
     */
    int insertSelective(PayRespLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_resp_log
     *
     * @mbg.generated
     */
    List<PayRespLog> selectByExampleWithBLOBs(PayRespLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_resp_log
     *
     * @mbg.generated
     */
    List<PayRespLog> selectByExample(PayRespLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_resp_log
     *
     * @mbg.generated
     */
    PayRespLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_resp_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PayRespLog record, @Param("example") PayRespLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_resp_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PayRespLog record, @Param("example") PayRespLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_resp_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PayRespLog record, @Param("example") PayRespLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_resp_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PayRespLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_resp_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(PayRespLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_resp_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayRespLog record);
}