package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.QuartzInfo;
import com.adpanshi.cashloan.manage.cl.model.QuartzInfoExample;
import java.util.List;
import java.util.Map;

import com.adpanshi.cashloan.manage.cl.model.expand.QuartzInfoModel;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface QuartzInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_quartz_info
     *
     * @mbg.generated
     */
    long countByExample(QuartzInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_quartz_info
     *
     * @mbg.generated
     */
    int deleteByExample(QuartzInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_quartz_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_quartz_info
     *
     * @mbg.generated
     */
    int insert(QuartzInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_quartz_info
     *
     * @mbg.generated
     */
    int insertSelective(QuartzInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_quartz_info
     *
     * @mbg.generated
     */
    List<QuartzInfo> selectByExample(QuartzInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_quartz_info
     *
     * @mbg.generated
     */
    QuartzInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_quartz_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QuartzInfo record, @Param("example") QuartzInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_quartz_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QuartzInfo record, @Param("example") QuartzInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_quartz_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(QuartzInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_quartz_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(QuartzInfo record);
    /**
     * 数据查询
     *
     * @param paramMap
     *            查询条件
     * @return 结果集
     */
    List<QuartzInfo> listSelective(Map<String, Object> paramMap);
    /**
     * 定时任务查询
     *
     * @param map
     * @return
     */
    List<QuartzInfoModel> page(Map<String, Object> map);
}