package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.SmsTpl;
import com.adpanshi.cashloan.manage.cl.model.SmsTplExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface SmsTplMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sms_tpl
     *
     * @mbg.generated
     */
    long countByExample(SmsTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sms_tpl
     *
     * @mbg.generated
     */
    int deleteByExample(SmsTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sms_tpl
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sms_tpl
     *
     * @mbg.generated
     */
    int insert(SmsTpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sms_tpl
     *
     * @mbg.generated
     */
    int insertSelective(SmsTpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sms_tpl
     *
     * @mbg.generated
     */
    List<SmsTpl> selectByExample(SmsTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sms_tpl
     *
     * @mbg.generated
     */
    SmsTpl selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sms_tpl
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SmsTpl record, @Param("example") SmsTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sms_tpl
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SmsTpl record, @Param("example") SmsTplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sms_tpl
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SmsTpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sms_tpl
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SmsTpl record);
}