package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.SysAttachment;
import com.adpanshi.cashloan.manage.cl.model.SysAttachmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface SysAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sys_attachment
     *
     * @mbg.generated
     */
    long countByExample(SysAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sys_attachment
     *
     * @mbg.generated
     */
    int deleteByExample(SysAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sys_attachment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sys_attachment
     *
     * @mbg.generated
     */
    int insert(SysAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sys_attachment
     *
     * @mbg.generated
     */
    int insertSelective(SysAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sys_attachment
     *
     * @mbg.generated
     */
    List<SysAttachment> selectByExample(SysAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sys_attachment
     *
     * @mbg.generated
     */
    SysAttachment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sys_attachment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysAttachment record, @Param("example") SysAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sys_attachment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysAttachment record, @Param("example") SysAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sys_attachment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sys_attachment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysAttachment record);
}