package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.UrgeRepayOrder;
import com.adpanshi.cashloan.manage.cl.model.UrgeRepayOrderExample;
import java.util.List;
import java.util.Map;

import com.adpanshi.cashloan.manage.cl.model.expand.UrgeRepayCountModel;
import com.adpanshi.cashloan.manage.cl.model.expand.UrgeRepayOrderModel;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface UrgeRepayOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_order
     *
     * @mbg.generated
     */
    long countByExample(UrgeRepayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_order
     *
     * @mbg.generated
     */
    int deleteByExample(UrgeRepayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_order
     *
     * @mbg.generated
     */
    int insert(UrgeRepayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_order
     *
     * @mbg.generated
     */
    int insertSelective(UrgeRepayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_order
     *
     * @mbg.generated
     */
    List<UrgeRepayOrder> selectByExample(UrgeRepayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_order
     *
     * @mbg.generated
     */
    UrgeRepayOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UrgeRepayOrder record, @Param("example") UrgeRepayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UrgeRepayOrder record, @Param("example") UrgeRepayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UrgeRepayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UrgeRepayOrder record);
    /**
     *  催收订单查询
     * @param params
     * @return List<UrgeRepayOrderModel>
     * @throws
     * @author Vic Tang
     * @date 2018/8/1 21:03
     * */
    List<UrgeRepayOrderModel>  listUrgeTotalOrder(Map<String, Object> params);

    List<UrgeRepayOrderModel> listModel(Map<String, Object> params);

    List<UrgeRepayCountModel> urgeCount(Map<String, Object> params);

    List<UrgeRepayCountModel> memberCount(Map<String, Object> params);

    List<UrgeRepayCountModel> orderCount(Map<String, Object> params);

    List<UrgeRepayCountModel> memberDayCount(Map<String, Object> params);

    List<UrgeRepayOrderModel> listManage(Map<String, Object> paramMap);

    int updateSelective(Map<String, Object> params);

    List<UrgeRepayOrder> listSelective(Map<String, Object> params);
}