package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.UrgeRepayLog;
import com.adpanshi.cashloan.manage.cl.model.UrgeRepayLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface UrgeRepayLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_log
     *
     * @mbg.generated
     */
    long countByExample(UrgeRepayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_log
     *
     * @mbg.generated
     */
    int deleteByExample(UrgeRepayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_log
     *
     * @mbg.generated
     */
    int insert(UrgeRepayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_log
     *
     * @mbg.generated
     */
    int insertSelective(UrgeRepayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_log
     *
     * @mbg.generated
     */
    List<UrgeRepayLog> selectByExample(UrgeRepayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_log
     *
     * @mbg.generated
     */
    UrgeRepayLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UrgeRepayLog record, @Param("example") UrgeRepayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UrgeRepayLog record, @Param("example") UrgeRepayLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UrgeRepayLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_urge_repay_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UrgeRepayLog record);
}