package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.UserIdnoMatchDict;
import com.adpanshi.cashloan.manage.cl.model.UserIdnoMatchDictExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface UserIdnoMatchDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_idno_match_dict
     *
     * @mbg.generated
     */
    long countByExample(UserIdnoMatchDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_idno_match_dict
     *
     * @mbg.generated
     */
    int deleteByExample(UserIdnoMatchDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_idno_match_dict
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_idno_match_dict
     *
     * @mbg.generated
     */
    int insert(UserIdnoMatchDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_idno_match_dict
     *
     * @mbg.generated
     */
    int insertSelective(UserIdnoMatchDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_idno_match_dict
     *
     * @mbg.generated
     */
    List<UserIdnoMatchDict> selectByExample(UserIdnoMatchDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_idno_match_dict
     *
     * @mbg.generated
     */
    UserIdnoMatchDict selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_idno_match_dict
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserIdnoMatchDict record, @Param("example") UserIdnoMatchDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_idno_match_dict
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserIdnoMatchDict record, @Param("example") UserIdnoMatchDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_idno_match_dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserIdnoMatchDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_idno_match_dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserIdnoMatchDict record);

    List<UserIdnoMatchDict> listSelective(Map<String, Object> params);
}