package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.UserBaseInfo;
import com.adpanshi.cashloan.manage.cl.model.UserBaseInfoExample;
import java.util.List;

import com.adpanshi.cashloan.manage.cl.model.expand.UserBaseInfoModel;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface UserBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_base_info
     *
     * @mbg.generated
     */
    long countByExample(UserBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_base_info
     *
     * @mbg.generated
     */
    int deleteByExample(UserBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_base_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_base_info
     *
     * @mbg.generated
     */
    int insert(UserBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_base_info
     *
     * @mbg.generated
     */
    int insertSelective(UserBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_base_info
     *
     * @mbg.generated
     */
    List<UserBaseInfo> selectByExample(UserBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_base_info
     *
     * @mbg.generated
     */
    UserBaseInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_base_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserBaseInfo record, @Param("example") UserBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_base_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserBaseInfo record, @Param("example") UserBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_base_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_base_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserBaseInfo record);
    /**
     *  根据用户id获取用户详情
     * @param userId
     * @return UserBaseInfoModel
     * @throws
     * @author Vic Tang
     * @date 2018/8/3 11:26
     * */
    UserBaseInfoModel getBaseModelByUserId(Long userId);
    /**
     * 待放款用户详情
     */
    List<UserBaseInfoModel> findLoanUserInfo();
}