package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.UserEmerContacts;
import com.adpanshi.cashloan.manage.cl.model.UserEmerContactsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface UserEmerContactsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_emer_contacts
     *
     * @mbg.generated
     */
    long countByExample(UserEmerContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_emer_contacts
     *
     * @mbg.generated
     */
    int deleteByExample(UserEmerContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_emer_contacts
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_emer_contacts
     *
     * @mbg.generated
     */
    int insert(UserEmerContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_emer_contacts
     *
     * @mbg.generated
     */
    int insertSelective(UserEmerContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_emer_contacts
     *
     * @mbg.generated
     */
    List<UserEmerContacts> selectByExample(UserEmerContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_emer_contacts
     *
     * @mbg.generated
     */
    UserEmerContacts selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_emer_contacts
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserEmerContacts record, @Param("example") UserEmerContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_emer_contacts
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserEmerContacts record, @Param("example") UserEmerContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_emer_contacts
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserEmerContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_emer_contacts
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserEmerContacts record);
}