package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.UserApps;
import com.adpanshi.cashloan.manage.cl.model.UserAppsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface UserAppsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_apps_1
     *
     * @mbg.generated
     */
    long countByExample(UserAppsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_apps_1
     *
     * @mbg.generated
     */
    int deleteByExample(UserAppsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_apps_1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_apps_1
     *
     * @mbg.generated
     */
    int insert(UserApps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_apps_1
     *
     * @mbg.generated
     */
    int insertSelective(UserApps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_apps_1
     *
     * @mbg.generated
     */
    List<UserApps> selectByExample(UserAppsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_apps_1
     *
     * @mbg.generated
     */
    UserApps selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_apps_1
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserApps record, @Param("example") UserAppsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_apps_1
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserApps record, @Param("example") UserAppsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_apps_1
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserApps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_apps_1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserApps record);
}