package com.adpanshi.cashloan.manage.cl.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.cl.model.UserContacts;
import com.adpanshi.cashloan.manage.cl.model.UserContactsExample;
import java.util.List;
import java.util.Map;

import com.adpanshi.cashloan.manage.cl.model.expand.UserContactsModel;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface UserContactsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_contacts_1
     *
     * @mbg.generated
     */
    long countByExample(UserContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_contacts_1
     *
     * @mbg.generated
     */
    int deleteByExample(UserContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_contacts_1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_contacts_1
     *
     * @mbg.generated
     */
    int insert(UserContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_contacts_1
     *
     * @mbg.generated
     */
    int insertSelective(UserContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_contacts_1
     *
     * @mbg.generated
     */
    List<UserContacts> selectByExample(UserContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_contacts_1
     *
     * @mbg.generated
     */
    UserContacts selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_contacts_1
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserContacts record, @Param("example") UserContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_contacts_1
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserContacts record, @Param("example") UserContactsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_contacts_1
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserContacts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_contacts_1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserContacts record);

    /**
     * 根据表名查询表数量
     * @param tableName
     * @return
     */
    int countTable(String tableName);
    /**
     * 做了字典匹配的通讯录
     * @param tableName
     * @param params
     * @return
     */
    List<UserContactsModel> listShardSelectiveNew(@Param("tableName") String tableName,
                                                  @Param("params") Map<String, Object> params);
}