package com.adpanshi.cashloan.manage.cl.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class PayLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.order_no
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.borrow_main_id
     *
     * @mbg.generated
     */
    private Long borrowMainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.amount
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.card_no
     *
     * @mbg.generated
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.bank
     *
     * @mbg.generated
     */
    private String bank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.confirm_code
     *
     * @mbg.generated
     */
    private String confirmCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.scenes
     *
     * @mbg.generated
     */
    private String scenes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.pay_req_time
     *
     * @mbg.generated
     */
    private Date payReqTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_pay_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_pay_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.id
     *
     * @return the value of cl_pay_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.id
     *
     * @param id the value for cl_pay_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.order_no
     *
     * @return the value of cl_pay_log.order_no
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.order_no
     *
     * @param orderNo the value for cl_pay_log.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.user_id
     *
     * @return the value of cl_pay_log.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.user_id
     *
     * @param userId the value for cl_pay_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.borrow_main_id
     *
     * @return the value of cl_pay_log.borrow_main_id
     *
     * @mbg.generated
     */
    public Long getBorrowMainId() {
        return borrowMainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.borrow_main_id
     *
     * @param borrowMainId the value for cl_pay_log.borrow_main_id
     *
     * @mbg.generated
     */
    public void setBorrowMainId(Long borrowMainId) {
        this.borrowMainId = borrowMainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.amount
     *
     * @return the value of cl_pay_log.amount
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.amount
     *
     * @param amount the value for cl_pay_log.amount
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.card_no
     *
     * @return the value of cl_pay_log.card_no
     *
     * @mbg.generated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.card_no
     *
     * @param cardNo the value for cl_pay_log.card_no
     *
     * @mbg.generated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.bank
     *
     * @return the value of cl_pay_log.bank
     *
     * @mbg.generated
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.bank
     *
     * @param bank the value for cl_pay_log.bank
     *
     * @mbg.generated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.confirm_code
     *
     * @return the value of cl_pay_log.confirm_code
     *
     * @mbg.generated
     */
    public String getConfirmCode() {
        return confirmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.confirm_code
     *
     * @param confirmCode the value for cl_pay_log.confirm_code
     *
     * @mbg.generated
     */
    public void setConfirmCode(String confirmCode) {
        this.confirmCode = confirmCode == null ? null : confirmCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.source
     *
     * @return the value of cl_pay_log.source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.source
     *
     * @param source the value for cl_pay_log.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.type
     *
     * @return the value of cl_pay_log.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.type
     *
     * @param type the value for cl_pay_log.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.scenes
     *
     * @return the value of cl_pay_log.scenes
     *
     * @mbg.generated
     */
    public String getScenes() {
        return scenes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.scenes
     *
     * @param scenes the value for cl_pay_log.scenes
     *
     * @mbg.generated
     */
    public void setScenes(String scenes) {
        this.scenes = scenes == null ? null : scenes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.state
     *
     * @return the value of cl_pay_log.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.state
     *
     * @param state the value for cl_pay_log.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.remark
     *
     * @return the value of cl_pay_log.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.remark
     *
     * @param remark the value for cl_pay_log.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.pay_req_time
     *
     * @return the value of cl_pay_log.pay_req_time
     *
     * @mbg.generated
     */
    public Date getPayReqTime() {
        return payReqTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.pay_req_time
     *
     * @param payReqTime the value for cl_pay_log.pay_req_time
     *
     * @mbg.generated
     */
    public void setPayReqTime(Date payReqTime) {
        this.payReqTime = payReqTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.update_time
     *
     * @return the value of cl_pay_log.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.update_time
     *
     * @param updateTime the value for cl_pay_log.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_pay_log.create_time
     *
     * @return the value of cl_pay_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_pay_log.create_time
     *
     * @param createTime the value for cl_pay_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_log
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PayLog other = (PayLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderNo() == null ? other.getOrderNo() == null : this.getOrderNo().equals(other.getOrderNo()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getBorrowMainId() == null ? other.getBorrowMainId() == null : this.getBorrowMainId().equals(other.getBorrowMainId()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getCardNo() == null ? other.getCardNo() == null : this.getCardNo().equals(other.getCardNo()))
            && (this.getBank() == null ? other.getBank() == null : this.getBank().equals(other.getBank()))
            && (this.getConfirmCode() == null ? other.getConfirmCode() == null : this.getConfirmCode().equals(other.getConfirmCode()))
            && (this.getSource() == null ? other.getSource() == null : this.getSource().equals(other.getSource()))
            && (this.getType() == null ? other.getType() == null : this.getType().equals(other.getType()))
            && (this.getScenes() == null ? other.getScenes() == null : this.getScenes().equals(other.getScenes()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getPayReqTime() == null ? other.getPayReqTime() == null : this.getPayReqTime().equals(other.getPayReqTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_pay_log
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderNo() == null) ? 0 : getOrderNo().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getBorrowMainId() == null) ? 0 : getBorrowMainId().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getCardNo() == null) ? 0 : getCardNo().hashCode());
        result = prime * result + ((getBank() == null) ? 0 : getBank().hashCode());
        result = prime * result + ((getConfirmCode() == null) ? 0 : getConfirmCode().hashCode());
        result = prime * result + ((getSource() == null) ? 0 : getSource().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getScenes() == null) ? 0 : getScenes().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getPayReqTime() == null) ? 0 : getPayReqTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }
}