package com.adpanshi.cashloan.manage.cl.model;

import java.io.Serializable;
import java.util.Date;

public class QuartzInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_quartz_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_quartz_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_quartz_info.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_quartz_info.cycle
     *
     * @mbg.generated
     */
    private String cycle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_quartz_info.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_quartz_info.succeed
     *
     * @mbg.generated
     */
    private Integer succeed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_quartz_info.fail
     *
     * @mbg.generated
     */
    private Integer fail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_quartz_info.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_quartz_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_quartz_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_quartz_info.id
     *
     * @return the value of cl_quartz_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_quartz_info.id
     *
     * @param id the value for cl_quartz_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_quartz_info.name
     *
     * @return the value of cl_quartz_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_quartz_info.name
     *
     * @param name the value for cl_quartz_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_quartz_info.code
     *
     * @return the value of cl_quartz_info.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_quartz_info.code
     *
     * @param code the value for cl_quartz_info.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_quartz_info.cycle
     *
     * @return the value of cl_quartz_info.cycle
     *
     * @mbg.generated
     */
    public String getCycle() {
        return cycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_quartz_info.cycle
     *
     * @param cycle the value for cl_quartz_info.cycle
     *
     * @mbg.generated
     */
    public void setCycle(String cycle) {
        this.cycle = cycle == null ? null : cycle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_quartz_info.class_name
     *
     * @return the value of cl_quartz_info.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_quartz_info.class_name
     *
     * @param className the value for cl_quartz_info.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_quartz_info.succeed
     *
     * @return the value of cl_quartz_info.succeed
     *
     * @mbg.generated
     */
    public Integer getSucceed() {
        return succeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_quartz_info.succeed
     *
     * @param succeed the value for cl_quartz_info.succeed
     *
     * @mbg.generated
     */
    public void setSucceed(Integer succeed) {
        this.succeed = succeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_quartz_info.fail
     *
     * @return the value of cl_quartz_info.fail
     *
     * @mbg.generated
     */
    public Integer getFail() {
        return fail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_quartz_info.fail
     *
     * @param fail the value for cl_quartz_info.fail
     *
     * @mbg.generated
     */
    public void setFail(Integer fail) {
        this.fail = fail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_quartz_info.state
     *
     * @return the value of cl_quartz_info.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_quartz_info.state
     *
     * @param state the value for cl_quartz_info.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_quartz_info.create_time
     *
     * @return the value of cl_quartz_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_quartz_info.create_time
     *
     * @param createTime the value for cl_quartz_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_quartz_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        QuartzInfo other = (QuartzInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getCycle() == null ? other.getCycle() == null : this.getCycle().equals(other.getCycle()))
            && (this.getClassName() == null ? other.getClassName() == null : this.getClassName().equals(other.getClassName()))
            && (this.getSucceed() == null ? other.getSucceed() == null : this.getSucceed().equals(other.getSucceed()))
            && (this.getFail() == null ? other.getFail() == null : this.getFail().equals(other.getFail()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_quartz_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getCycle() == null) ? 0 : getCycle().hashCode());
        result = prime * result + ((getClassName() == null) ? 0 : getClassName().hashCode());
        result = prime * result + ((getSucceed() == null) ? 0 : getSucceed().hashCode());
        result = prime * result + ((getFail() == null) ? 0 : getFail().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        return result;
    }
}