package com.adpanshi.cashloan.manage.cl.model;

import java.io.Serializable;
import java.util.Date;

public class Sms implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_sms.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_sms.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_sms.send_time
     *
     * @mbg.generated
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_sms.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_sms.resp_time
     *
     * @mbg.generated
     */
    private Date respTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_sms.resp
     *
     * @mbg.generated
     */
    private String resp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_sms.sms_type
     *
     * @mbg.generated
     */
    private String smsType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_sms.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_sms.order_no
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_sms.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_sms.verify_time
     *
     * @mbg.generated
     */
    private Integer verifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_sms.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_sms.msgid
     *
     * @mbg.generated
     */
    private String msgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_sms.resp_state
     *
     * @mbg.generated
     */
    private String respState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_sms.sms_platform
     *
     * @mbg.generated
     */
    private String smsPlatform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_sms
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_sms.id
     *
     * @return the value of cl_sms.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_sms.id
     *
     * @param id the value for cl_sms.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_sms.phone
     *
     * @return the value of cl_sms.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_sms.phone
     *
     * @param phone the value for cl_sms.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_sms.send_time
     *
     * @return the value of cl_sms.send_time
     *
     * @mbg.generated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_sms.send_time
     *
     * @param sendTime the value for cl_sms.send_time
     *
     * @mbg.generated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_sms.content
     *
     * @return the value of cl_sms.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_sms.content
     *
     * @param content the value for cl_sms.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_sms.resp_time
     *
     * @return the value of cl_sms.resp_time
     *
     * @mbg.generated
     */
    public Date getRespTime() {
        return respTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_sms.resp_time
     *
     * @param respTime the value for cl_sms.resp_time
     *
     * @mbg.generated
     */
    public void setRespTime(Date respTime) {
        this.respTime = respTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_sms.resp
     *
     * @return the value of cl_sms.resp
     *
     * @mbg.generated
     */
    public String getResp() {
        return resp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_sms.resp
     *
     * @param resp the value for cl_sms.resp
     *
     * @mbg.generated
     */
    public void setResp(String resp) {
        this.resp = resp == null ? null : resp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_sms.sms_type
     *
     * @return the value of cl_sms.sms_type
     *
     * @mbg.generated
     */
    public String getSmsType() {
        return smsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_sms.sms_type
     *
     * @param smsType the value for cl_sms.sms_type
     *
     * @mbg.generated
     */
    public void setSmsType(String smsType) {
        this.smsType = smsType == null ? null : smsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_sms.code
     *
     * @return the value of cl_sms.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_sms.code
     *
     * @param code the value for cl_sms.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_sms.order_no
     *
     * @return the value of cl_sms.order_no
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_sms.order_no
     *
     * @param orderNo the value for cl_sms.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_sms.state
     *
     * @return the value of cl_sms.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_sms.state
     *
     * @param state the value for cl_sms.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_sms.verify_time
     *
     * @return the value of cl_sms.verify_time
     *
     * @mbg.generated
     */
    public Integer getVerifyTime() {
        return verifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_sms.verify_time
     *
     * @param verifyTime the value for cl_sms.verify_time
     *
     * @mbg.generated
     */
    public void setVerifyTime(Integer verifyTime) {
        this.verifyTime = verifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_sms.email
     *
     * @return the value of cl_sms.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_sms.email
     *
     * @param email the value for cl_sms.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_sms.msgid
     *
     * @return the value of cl_sms.msgid
     *
     * @mbg.generated
     */
    public String getMsgid() {
        return msgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_sms.msgid
     *
     * @param msgid the value for cl_sms.msgid
     *
     * @mbg.generated
     */
    public void setMsgid(String msgid) {
        this.msgid = msgid == null ? null : msgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_sms.resp_state
     *
     * @return the value of cl_sms.resp_state
     *
     * @mbg.generated
     */
    public String getRespState() {
        return respState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_sms.resp_state
     *
     * @param respState the value for cl_sms.resp_state
     *
     * @mbg.generated
     */
    public void setRespState(String respState) {
        this.respState = respState == null ? null : respState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_sms.sms_platform
     *
     * @return the value of cl_sms.sms_platform
     *
     * @mbg.generated
     */
    public String getSmsPlatform() {
        return smsPlatform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_sms.sms_platform
     *
     * @param smsPlatform the value for cl_sms.sms_platform
     *
     * @mbg.generated
     */
    public void setSmsPlatform(String smsPlatform) {
        this.smsPlatform = smsPlatform == null ? null : smsPlatform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sms
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Sms other = (Sms) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getSendTime() == null ? other.getSendTime() == null : this.getSendTime().equals(other.getSendTime()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
            && (this.getRespTime() == null ? other.getRespTime() == null : this.getRespTime().equals(other.getRespTime()))
            && (this.getResp() == null ? other.getResp() == null : this.getResp().equals(other.getResp()))
            && (this.getSmsType() == null ? other.getSmsType() == null : this.getSmsType().equals(other.getSmsType()))
            && (this.getCode() == null ? other.getCode() == null : this.getCode().equals(other.getCode()))
            && (this.getOrderNo() == null ? other.getOrderNo() == null : this.getOrderNo().equals(other.getOrderNo()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getVerifyTime() == null ? other.getVerifyTime() == null : this.getVerifyTime().equals(other.getVerifyTime()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getMsgid() == null ? other.getMsgid() == null : this.getMsgid().equals(other.getMsgid()))
            && (this.getRespState() == null ? other.getRespState() == null : this.getRespState().equals(other.getRespState()))
            && (this.getSmsPlatform() == null ? other.getSmsPlatform() == null : this.getSmsPlatform().equals(other.getSmsPlatform()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_sms
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getSendTime() == null) ? 0 : getSendTime().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getRespTime() == null) ? 0 : getRespTime().hashCode());
        result = prime * result + ((getResp() == null) ? 0 : getResp().hashCode());
        result = prime * result + ((getSmsType() == null) ? 0 : getSmsType().hashCode());
        result = prime * result + ((getCode() == null) ? 0 : getCode().hashCode());
        result = prime * result + ((getOrderNo() == null) ? 0 : getOrderNo().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getVerifyTime() == null) ? 0 : getVerifyTime().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getMsgid() == null) ? 0 : getMsgid().hashCode());
        result = prime * result + ((getRespState() == null) ? 0 : getRespState().hashCode());
        result = prime * result + ((getSmsPlatform() == null) ? 0 : getSmsPlatform().hashCode());
        return result;
    }
}