package com.adpanshi.cashloan.manage.cl.model;

import java.io.Serializable;
import java.util.Date;

public class UserAuth implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.id_state
     *
     * @mbg.generated
     */
    private String idState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.id_state_time
     *
     * @mbg.generated
     */
    private Date idStateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.contact_state
     *
     * @mbg.generated
     */
    private String contactState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.contact_state_time
     *
     * @mbg.generated
     */
    private Date contactStateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.bank_card_state
     *
     * @mbg.generated
     */
    private String bankCardState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.bank_card_state_time
     *
     * @mbg.generated
     */
    private Date bankCardStateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.bank_card_bill_state
     *
     * @mbg.generated
     */
    private String bankCardBillState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.bank_card_bill_time
     *
     * @mbg.generated
     */
    private Date bankCardBillTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.gong_ji_jin_state
     *
     * @mbg.generated
     */
    private String gongJiJinState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.gong_ji_jin_time
     *
     * @mbg.generated
     */
    private Date gongJiJinTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.she_bao_state
     *
     * @mbg.generated
     */
    private String sheBaoState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.she_bao_time
     *
     * @mbg.generated
     */
    private Date sheBaoTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.phone_state
     *
     * @mbg.generated
     */
    private String phoneState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.phone_state_time
     *
     * @mbg.generated
     */
    private Date phoneStateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.zhima_state
     *
     * @mbg.generated
     */
    private String zhimaState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.zhima_state_time
     *
     * @mbg.generated
     */
    private Date zhimaStateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.work_info_state
     *
     * @mbg.generated
     */
    private String workInfoState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.work_info_state_time
     *
     * @mbg.generated
     */
    private Date workInfoStateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.other_info_state
     *
     * @mbg.generated
     */
    private String otherInfoState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.other_info_state_time
     *
     * @mbg.generated
     */
    private Date otherInfoStateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.living_identify_state
     *
     * @mbg.generated
     */
    private String livingIdentifyState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.living_identify_state_time
     *
     * @mbg.generated
     */
    private Date livingIdentifyStateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.tongdun_state
     *
     * @mbg.generated
     */
    private String tongdunState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.tongdun_state_time
     *
     * @mbg.generated
     */
    private Date tongdunStateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.tenement_income_state
     *
     * @mbg.generated
     */
    private String tenementIncomeState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.tenement_income_time
     *
     * @mbg.generated
     */
    private Date tenementIncomeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.new_version
     *
     * @mbg.generated
     */
    private Byte newVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.pan_state
     *
     * @mbg.generated
     */
    private String panState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_auth.pan_state_time
     *
     * @mbg.generated
     */
    private Date panStateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_user_auth
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.id
     *
     * @return the value of cl_user_auth.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.id
     *
     * @param id the value for cl_user_auth.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.user_id
     *
     * @return the value of cl_user_auth.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.user_id
     *
     * @param userId the value for cl_user_auth.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.id_state
     *
     * @return the value of cl_user_auth.id_state
     *
     * @mbg.generated
     */
    public String getIdState() {
        return idState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.id_state
     *
     * @param idState the value for cl_user_auth.id_state
     *
     * @mbg.generated
     */
    public void setIdState(String idState) {
        this.idState = idState == null ? null : idState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.id_state_time
     *
     * @return the value of cl_user_auth.id_state_time
     *
     * @mbg.generated
     */
    public Date getIdStateTime() {
        return idStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.id_state_time
     *
     * @param idStateTime the value for cl_user_auth.id_state_time
     *
     * @mbg.generated
     */
    public void setIdStateTime(Date idStateTime) {
        this.idStateTime = idStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.contact_state
     *
     * @return the value of cl_user_auth.contact_state
     *
     * @mbg.generated
     */
    public String getContactState() {
        return contactState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.contact_state
     *
     * @param contactState the value for cl_user_auth.contact_state
     *
     * @mbg.generated
     */
    public void setContactState(String contactState) {
        this.contactState = contactState == null ? null : contactState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.contact_state_time
     *
     * @return the value of cl_user_auth.contact_state_time
     *
     * @mbg.generated
     */
    public Date getContactStateTime() {
        return contactStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.contact_state_time
     *
     * @param contactStateTime the value for cl_user_auth.contact_state_time
     *
     * @mbg.generated
     */
    public void setContactStateTime(Date contactStateTime) {
        this.contactStateTime = contactStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.bank_card_state
     *
     * @return the value of cl_user_auth.bank_card_state
     *
     * @mbg.generated
     */
    public String getBankCardState() {
        return bankCardState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.bank_card_state
     *
     * @param bankCardState the value for cl_user_auth.bank_card_state
     *
     * @mbg.generated
     */
    public void setBankCardState(String bankCardState) {
        this.bankCardState = bankCardState == null ? null : bankCardState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.bank_card_state_time
     *
     * @return the value of cl_user_auth.bank_card_state_time
     *
     * @mbg.generated
     */
    public Date getBankCardStateTime() {
        return bankCardStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.bank_card_state_time
     *
     * @param bankCardStateTime the value for cl_user_auth.bank_card_state_time
     *
     * @mbg.generated
     */
    public void setBankCardStateTime(Date bankCardStateTime) {
        this.bankCardStateTime = bankCardStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.bank_card_bill_state
     *
     * @return the value of cl_user_auth.bank_card_bill_state
     *
     * @mbg.generated
     */
    public String getBankCardBillState() {
        return bankCardBillState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.bank_card_bill_state
     *
     * @param bankCardBillState the value for cl_user_auth.bank_card_bill_state
     *
     * @mbg.generated
     */
    public void setBankCardBillState(String bankCardBillState) {
        this.bankCardBillState = bankCardBillState == null ? null : bankCardBillState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.bank_card_bill_time
     *
     * @return the value of cl_user_auth.bank_card_bill_time
     *
     * @mbg.generated
     */
    public Date getBankCardBillTime() {
        return bankCardBillTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.bank_card_bill_time
     *
     * @param bankCardBillTime the value for cl_user_auth.bank_card_bill_time
     *
     * @mbg.generated
     */
    public void setBankCardBillTime(Date bankCardBillTime) {
        this.bankCardBillTime = bankCardBillTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.gong_ji_jin_state
     *
     * @return the value of cl_user_auth.gong_ji_jin_state
     *
     * @mbg.generated
     */
    public String getGongJiJinState() {
        return gongJiJinState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.gong_ji_jin_state
     *
     * @param gongJiJinState the value for cl_user_auth.gong_ji_jin_state
     *
     * @mbg.generated
     */
    public void setGongJiJinState(String gongJiJinState) {
        this.gongJiJinState = gongJiJinState == null ? null : gongJiJinState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.gong_ji_jin_time
     *
     * @return the value of cl_user_auth.gong_ji_jin_time
     *
     * @mbg.generated
     */
    public Date getGongJiJinTime() {
        return gongJiJinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.gong_ji_jin_time
     *
     * @param gongJiJinTime the value for cl_user_auth.gong_ji_jin_time
     *
     * @mbg.generated
     */
    public void setGongJiJinTime(Date gongJiJinTime) {
        this.gongJiJinTime = gongJiJinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.she_bao_state
     *
     * @return the value of cl_user_auth.she_bao_state
     *
     * @mbg.generated
     */
    public String getSheBaoState() {
        return sheBaoState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.she_bao_state
     *
     * @param sheBaoState the value for cl_user_auth.she_bao_state
     *
     * @mbg.generated
     */
    public void setSheBaoState(String sheBaoState) {
        this.sheBaoState = sheBaoState == null ? null : sheBaoState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.she_bao_time
     *
     * @return the value of cl_user_auth.she_bao_time
     *
     * @mbg.generated
     */
    public Date getSheBaoTime() {
        return sheBaoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.she_bao_time
     *
     * @param sheBaoTime the value for cl_user_auth.she_bao_time
     *
     * @mbg.generated
     */
    public void setSheBaoTime(Date sheBaoTime) {
        this.sheBaoTime = sheBaoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.phone_state
     *
     * @return the value of cl_user_auth.phone_state
     *
     * @mbg.generated
     */
    public String getPhoneState() {
        return phoneState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.phone_state
     *
     * @param phoneState the value for cl_user_auth.phone_state
     *
     * @mbg.generated
     */
    public void setPhoneState(String phoneState) {
        this.phoneState = phoneState == null ? null : phoneState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.phone_state_time
     *
     * @return the value of cl_user_auth.phone_state_time
     *
     * @mbg.generated
     */
    public Date getPhoneStateTime() {
        return phoneStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.phone_state_time
     *
     * @param phoneStateTime the value for cl_user_auth.phone_state_time
     *
     * @mbg.generated
     */
    public void setPhoneStateTime(Date phoneStateTime) {
        this.phoneStateTime = phoneStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.zhima_state
     *
     * @return the value of cl_user_auth.zhima_state
     *
     * @mbg.generated
     */
    public String getZhimaState() {
        return zhimaState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.zhima_state
     *
     * @param zhimaState the value for cl_user_auth.zhima_state
     *
     * @mbg.generated
     */
    public void setZhimaState(String zhimaState) {
        this.zhimaState = zhimaState == null ? null : zhimaState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.zhima_state_time
     *
     * @return the value of cl_user_auth.zhima_state_time
     *
     * @mbg.generated
     */
    public Date getZhimaStateTime() {
        return zhimaStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.zhima_state_time
     *
     * @param zhimaStateTime the value for cl_user_auth.zhima_state_time
     *
     * @mbg.generated
     */
    public void setZhimaStateTime(Date zhimaStateTime) {
        this.zhimaStateTime = zhimaStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.work_info_state
     *
     * @return the value of cl_user_auth.work_info_state
     *
     * @mbg.generated
     */
    public String getWorkInfoState() {
        return workInfoState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.work_info_state
     *
     * @param workInfoState the value for cl_user_auth.work_info_state
     *
     * @mbg.generated
     */
    public void setWorkInfoState(String workInfoState) {
        this.workInfoState = workInfoState == null ? null : workInfoState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.work_info_state_time
     *
     * @return the value of cl_user_auth.work_info_state_time
     *
     * @mbg.generated
     */
    public Date getWorkInfoStateTime() {
        return workInfoStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.work_info_state_time
     *
     * @param workInfoStateTime the value for cl_user_auth.work_info_state_time
     *
     * @mbg.generated
     */
    public void setWorkInfoStateTime(Date workInfoStateTime) {
        this.workInfoStateTime = workInfoStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.other_info_state
     *
     * @return the value of cl_user_auth.other_info_state
     *
     * @mbg.generated
     */
    public String getOtherInfoState() {
        return otherInfoState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.other_info_state
     *
     * @param otherInfoState the value for cl_user_auth.other_info_state
     *
     * @mbg.generated
     */
    public void setOtherInfoState(String otherInfoState) {
        this.otherInfoState = otherInfoState == null ? null : otherInfoState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.other_info_state_time
     *
     * @return the value of cl_user_auth.other_info_state_time
     *
     * @mbg.generated
     */
    public Date getOtherInfoStateTime() {
        return otherInfoStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.other_info_state_time
     *
     * @param otherInfoStateTime the value for cl_user_auth.other_info_state_time
     *
     * @mbg.generated
     */
    public void setOtherInfoStateTime(Date otherInfoStateTime) {
        this.otherInfoStateTime = otherInfoStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.living_identify_state
     *
     * @return the value of cl_user_auth.living_identify_state
     *
     * @mbg.generated
     */
    public String getLivingIdentifyState() {
        return livingIdentifyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.living_identify_state
     *
     * @param livingIdentifyState the value for cl_user_auth.living_identify_state
     *
     * @mbg.generated
     */
    public void setLivingIdentifyState(String livingIdentifyState) {
        this.livingIdentifyState = livingIdentifyState == null ? null : livingIdentifyState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.living_identify_state_time
     *
     * @return the value of cl_user_auth.living_identify_state_time
     *
     * @mbg.generated
     */
    public Date getLivingIdentifyStateTime() {
        return livingIdentifyStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.living_identify_state_time
     *
     * @param livingIdentifyStateTime the value for cl_user_auth.living_identify_state_time
     *
     * @mbg.generated
     */
    public void setLivingIdentifyStateTime(Date livingIdentifyStateTime) {
        this.livingIdentifyStateTime = livingIdentifyStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.tongdun_state
     *
     * @return the value of cl_user_auth.tongdun_state
     *
     * @mbg.generated
     */
    public String getTongdunState() {
        return tongdunState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.tongdun_state
     *
     * @param tongdunState the value for cl_user_auth.tongdun_state
     *
     * @mbg.generated
     */
    public void setTongdunState(String tongdunState) {
        this.tongdunState = tongdunState == null ? null : tongdunState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.tongdun_state_time
     *
     * @return the value of cl_user_auth.tongdun_state_time
     *
     * @mbg.generated
     */
    public Date getTongdunStateTime() {
        return tongdunStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.tongdun_state_time
     *
     * @param tongdunStateTime the value for cl_user_auth.tongdun_state_time
     *
     * @mbg.generated
     */
    public void setTongdunStateTime(Date tongdunStateTime) {
        this.tongdunStateTime = tongdunStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.tenement_income_state
     *
     * @return the value of cl_user_auth.tenement_income_state
     *
     * @mbg.generated
     */
    public String getTenementIncomeState() {
        return tenementIncomeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.tenement_income_state
     *
     * @param tenementIncomeState the value for cl_user_auth.tenement_income_state
     *
     * @mbg.generated
     */
    public void setTenementIncomeState(String tenementIncomeState) {
        this.tenementIncomeState = tenementIncomeState == null ? null : tenementIncomeState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.tenement_income_time
     *
     * @return the value of cl_user_auth.tenement_income_time
     *
     * @mbg.generated
     */
    public Date getTenementIncomeTime() {
        return tenementIncomeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.tenement_income_time
     *
     * @param tenementIncomeTime the value for cl_user_auth.tenement_income_time
     *
     * @mbg.generated
     */
    public void setTenementIncomeTime(Date tenementIncomeTime) {
        this.tenementIncomeTime = tenementIncomeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.new_version
     *
     * @return the value of cl_user_auth.new_version
     *
     * @mbg.generated
     */
    public Byte getNewVersion() {
        return newVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.new_version
     *
     * @param newVersion the value for cl_user_auth.new_version
     *
     * @mbg.generated
     */
    public void setNewVersion(Byte newVersion) {
        this.newVersion = newVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.pan_state
     *
     * @return the value of cl_user_auth.pan_state
     *
     * @mbg.generated
     */
    public String getPanState() {
        return panState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.pan_state
     *
     * @param panState the value for cl_user_auth.pan_state
     *
     * @mbg.generated
     */
    public void setPanState(String panState) {
        this.panState = panState == null ? null : panState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_auth.pan_state_time
     *
     * @return the value of cl_user_auth.pan_state_time
     *
     * @mbg.generated
     */
    public Date getPanStateTime() {
        return panStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_auth.pan_state_time
     *
     * @param panStateTime the value for cl_user_auth.pan_state_time
     *
     * @mbg.generated
     */
    public void setPanStateTime(Date panStateTime) {
        this.panStateTime = panStateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_auth
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserAuth other = (UserAuth) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getIdState() == null ? other.getIdState() == null : this.getIdState().equals(other.getIdState()))
            && (this.getIdStateTime() == null ? other.getIdStateTime() == null : this.getIdStateTime().equals(other.getIdStateTime()))
            && (this.getContactState() == null ? other.getContactState() == null : this.getContactState().equals(other.getContactState()))
            && (this.getContactStateTime() == null ? other.getContactStateTime() == null : this.getContactStateTime().equals(other.getContactStateTime()))
            && (this.getBankCardState() == null ? other.getBankCardState() == null : this.getBankCardState().equals(other.getBankCardState()))
            && (this.getBankCardStateTime() == null ? other.getBankCardStateTime() == null : this.getBankCardStateTime().equals(other.getBankCardStateTime()))
            && (this.getBankCardBillState() == null ? other.getBankCardBillState() == null : this.getBankCardBillState().equals(other.getBankCardBillState()))
            && (this.getBankCardBillTime() == null ? other.getBankCardBillTime() == null : this.getBankCardBillTime().equals(other.getBankCardBillTime()))
            && (this.getGongJiJinState() == null ? other.getGongJiJinState() == null : this.getGongJiJinState().equals(other.getGongJiJinState()))
            && (this.getGongJiJinTime() == null ? other.getGongJiJinTime() == null : this.getGongJiJinTime().equals(other.getGongJiJinTime()))
            && (this.getSheBaoState() == null ? other.getSheBaoState() == null : this.getSheBaoState().equals(other.getSheBaoState()))
            && (this.getSheBaoTime() == null ? other.getSheBaoTime() == null : this.getSheBaoTime().equals(other.getSheBaoTime()))
            && (this.getPhoneState() == null ? other.getPhoneState() == null : this.getPhoneState().equals(other.getPhoneState()))
            && (this.getPhoneStateTime() == null ? other.getPhoneStateTime() == null : this.getPhoneStateTime().equals(other.getPhoneStateTime()))
            && (this.getZhimaState() == null ? other.getZhimaState() == null : this.getZhimaState().equals(other.getZhimaState()))
            && (this.getZhimaStateTime() == null ? other.getZhimaStateTime() == null : this.getZhimaStateTime().equals(other.getZhimaStateTime()))
            && (this.getWorkInfoState() == null ? other.getWorkInfoState() == null : this.getWorkInfoState().equals(other.getWorkInfoState()))
            && (this.getWorkInfoStateTime() == null ? other.getWorkInfoStateTime() == null : this.getWorkInfoStateTime().equals(other.getWorkInfoStateTime()))
            && (this.getOtherInfoState() == null ? other.getOtherInfoState() == null : this.getOtherInfoState().equals(other.getOtherInfoState()))
            && (this.getOtherInfoStateTime() == null ? other.getOtherInfoStateTime() == null : this.getOtherInfoStateTime().equals(other.getOtherInfoStateTime()))
            && (this.getLivingIdentifyState() == null ? other.getLivingIdentifyState() == null : this.getLivingIdentifyState().equals(other.getLivingIdentifyState()))
            && (this.getLivingIdentifyStateTime() == null ? other.getLivingIdentifyStateTime() == null : this.getLivingIdentifyStateTime().equals(other.getLivingIdentifyStateTime()))
            && (this.getTongdunState() == null ? other.getTongdunState() == null : this.getTongdunState().equals(other.getTongdunState()))
            && (this.getTongdunStateTime() == null ? other.getTongdunStateTime() == null : this.getTongdunStateTime().equals(other.getTongdunStateTime()))
            && (this.getTenementIncomeState() == null ? other.getTenementIncomeState() == null : this.getTenementIncomeState().equals(other.getTenementIncomeState()))
            && (this.getTenementIncomeTime() == null ? other.getTenementIncomeTime() == null : this.getTenementIncomeTime().equals(other.getTenementIncomeTime()))
            && (this.getNewVersion() == null ? other.getNewVersion() == null : this.getNewVersion().equals(other.getNewVersion()))
            && (this.getPanState() == null ? other.getPanState() == null : this.getPanState().equals(other.getPanState()))
            && (this.getPanStateTime() == null ? other.getPanStateTime() == null : this.getPanStateTime().equals(other.getPanStateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_auth
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getIdState() == null) ? 0 : getIdState().hashCode());
        result = prime * result + ((getIdStateTime() == null) ? 0 : getIdStateTime().hashCode());
        result = prime * result + ((getContactState() == null) ? 0 : getContactState().hashCode());
        result = prime * result + ((getContactStateTime() == null) ? 0 : getContactStateTime().hashCode());
        result = prime * result + ((getBankCardState() == null) ? 0 : getBankCardState().hashCode());
        result = prime * result + ((getBankCardStateTime() == null) ? 0 : getBankCardStateTime().hashCode());
        result = prime * result + ((getBankCardBillState() == null) ? 0 : getBankCardBillState().hashCode());
        result = prime * result + ((getBankCardBillTime() == null) ? 0 : getBankCardBillTime().hashCode());
        result = prime * result + ((getGongJiJinState() == null) ? 0 : getGongJiJinState().hashCode());
        result = prime * result + ((getGongJiJinTime() == null) ? 0 : getGongJiJinTime().hashCode());
        result = prime * result + ((getSheBaoState() == null) ? 0 : getSheBaoState().hashCode());
        result = prime * result + ((getSheBaoTime() == null) ? 0 : getSheBaoTime().hashCode());
        result = prime * result + ((getPhoneState() == null) ? 0 : getPhoneState().hashCode());
        result = prime * result + ((getPhoneStateTime() == null) ? 0 : getPhoneStateTime().hashCode());
        result = prime * result + ((getZhimaState() == null) ? 0 : getZhimaState().hashCode());
        result = prime * result + ((getZhimaStateTime() == null) ? 0 : getZhimaStateTime().hashCode());
        result = prime * result + ((getWorkInfoState() == null) ? 0 : getWorkInfoState().hashCode());
        result = prime * result + ((getWorkInfoStateTime() == null) ? 0 : getWorkInfoStateTime().hashCode());
        result = prime * result + ((getOtherInfoState() == null) ? 0 : getOtherInfoState().hashCode());
        result = prime * result + ((getOtherInfoStateTime() == null) ? 0 : getOtherInfoStateTime().hashCode());
        result = prime * result + ((getLivingIdentifyState() == null) ? 0 : getLivingIdentifyState().hashCode());
        result = prime * result + ((getLivingIdentifyStateTime() == null) ? 0 : getLivingIdentifyStateTime().hashCode());
        result = prime * result + ((getTongdunState() == null) ? 0 : getTongdunState().hashCode());
        result = prime * result + ((getTongdunStateTime() == null) ? 0 : getTongdunStateTime().hashCode());
        result = prime * result + ((getTenementIncomeState() == null) ? 0 : getTenementIncomeState().hashCode());
        result = prime * result + ((getTenementIncomeTime() == null) ? 0 : getTenementIncomeTime().hashCode());
        result = prime * result + ((getNewVersion() == null) ? 0 : getNewVersion().hashCode());
        result = prime * result + ((getPanState() == null) ? 0 : getPanState().hashCode());
        result = prime * result + ((getPanStateTime() == null) ? 0 : getPanStateTime().hashCode());
        return result;
    }
}