package com.adpanshi.cashloan.manage.cl.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.login_name
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.login_name_email
     *
     * @mbg.generated
     */
    private String loginNameEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.login_pwd
     *
     * @mbg.generated
     */
    private String loginPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.loginpwd_modify_time
     *
     * @mbg.generated
     */
    private Date loginpwdModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.regist_time
     *
     * @mbg.generated
     */
    private Date registTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.register_client
     *
     * @mbg.generated
     */
    private String registerClient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.trade_pwd
     *
     * @mbg.generated
     */
    private String tradePwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.tradepwd_modify_time
     *
     * @mbg.generated
     */
    private Date tradepwdModifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.invitation_code
     *
     * @mbg.generated
     */
    private String invitationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.channel_id
     *
     * @mbg.generated
     */
    private Long channelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.level
     *
     * @mbg.generated
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.login_time
     *
     * @mbg.generated
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.id
     *
     * @return the value of cl_user.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.id
     *
     * @param id the value for cl_user.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.uuid
     *
     * @return the value of cl_user.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.uuid
     *
     * @param uuid the value for cl_user.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.login_name
     *
     * @return the value of cl_user.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.login_name
     *
     * @param loginName the value for cl_user.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.login_name_email
     *
     * @return the value of cl_user.login_name_email
     *
     * @mbg.generated
     */
    public String getLoginNameEmail() {
        return loginNameEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.login_name_email
     *
     * @param loginNameEmail the value for cl_user.login_name_email
     *
     * @mbg.generated
     */
    public void setLoginNameEmail(String loginNameEmail) {
        this.loginNameEmail = loginNameEmail == null ? null : loginNameEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.login_pwd
     *
     * @return the value of cl_user.login_pwd
     *
     * @mbg.generated
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.login_pwd
     *
     * @param loginPwd the value for cl_user.login_pwd
     *
     * @mbg.generated
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.loginpwd_modify_time
     *
     * @return the value of cl_user.loginpwd_modify_time
     *
     * @mbg.generated
     */
    public Date getLoginpwdModifyTime() {
        return loginpwdModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.loginpwd_modify_time
     *
     * @param loginpwdModifyTime the value for cl_user.loginpwd_modify_time
     *
     * @mbg.generated
     */
    public void setLoginpwdModifyTime(Date loginpwdModifyTime) {
        this.loginpwdModifyTime = loginpwdModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.regist_time
     *
     * @return the value of cl_user.regist_time
     *
     * @mbg.generated
     */
    public Date getRegistTime() {
        return registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.regist_time
     *
     * @param registTime the value for cl_user.regist_time
     *
     * @mbg.generated
     */
    public void setRegistTime(Date registTime) {
        this.registTime = registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.register_client
     *
     * @return the value of cl_user.register_client
     *
     * @mbg.generated
     */
    public String getRegisterClient() {
        return registerClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.register_client
     *
     * @param registerClient the value for cl_user.register_client
     *
     * @mbg.generated
     */
    public void setRegisterClient(String registerClient) {
        this.registerClient = registerClient == null ? null : registerClient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.trade_pwd
     *
     * @return the value of cl_user.trade_pwd
     *
     * @mbg.generated
     */
    public String getTradePwd() {
        return tradePwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.trade_pwd
     *
     * @param tradePwd the value for cl_user.trade_pwd
     *
     * @mbg.generated
     */
    public void setTradePwd(String tradePwd) {
        this.tradePwd = tradePwd == null ? null : tradePwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.tradepwd_modify_time
     *
     * @return the value of cl_user.tradepwd_modify_time
     *
     * @mbg.generated
     */
    public Date getTradepwdModifyTime() {
        return tradepwdModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.tradepwd_modify_time
     *
     * @param tradepwdModifyTime the value for cl_user.tradepwd_modify_time
     *
     * @mbg.generated
     */
    public void setTradepwdModifyTime(Date tradepwdModifyTime) {
        this.tradepwdModifyTime = tradepwdModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.invitation_code
     *
     * @return the value of cl_user.invitation_code
     *
     * @mbg.generated
     */
    public String getInvitationCode() {
        return invitationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.invitation_code
     *
     * @param invitationCode the value for cl_user.invitation_code
     *
     * @mbg.generated
     */
    public void setInvitationCode(String invitationCode) {
        this.invitationCode = invitationCode == null ? null : invitationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.channel_id
     *
     * @return the value of cl_user.channel_id
     *
     * @mbg.generated
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.channel_id
     *
     * @param channelId the value for cl_user.channel_id
     *
     * @mbg.generated
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.level
     *
     * @return the value of cl_user.level
     *
     * @mbg.generated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.level
     *
     * @param level the value for cl_user.level
     *
     * @mbg.generated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.login_time
     *
     * @return the value of cl_user.login_time
     *
     * @mbg.generated
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.login_time
     *
     * @param loginTime the value for cl_user.login_time
     *
     * @mbg.generated
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.state
     *
     * @return the value of cl_user.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.state
     *
     * @param state the value for cl_user.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user.remark
     *
     * @return the value of cl_user.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user.remark
     *
     * @param remark the value for cl_user.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUuid() == null ? other.getUuid() == null : this.getUuid().equals(other.getUuid()))
            && (this.getLoginName() == null ? other.getLoginName() == null : this.getLoginName().equals(other.getLoginName()))
            && (this.getLoginNameEmail() == null ? other.getLoginNameEmail() == null : this.getLoginNameEmail().equals(other.getLoginNameEmail()))
            && (this.getLoginPwd() == null ? other.getLoginPwd() == null : this.getLoginPwd().equals(other.getLoginPwd()))
            && (this.getLoginpwdModifyTime() == null ? other.getLoginpwdModifyTime() == null : this.getLoginpwdModifyTime().equals(other.getLoginpwdModifyTime()))
            && (this.getRegistTime() == null ? other.getRegistTime() == null : this.getRegistTime().equals(other.getRegistTime()))
            && (this.getRegisterClient() == null ? other.getRegisterClient() == null : this.getRegisterClient().equals(other.getRegisterClient()))
            && (this.getTradePwd() == null ? other.getTradePwd() == null : this.getTradePwd().equals(other.getTradePwd()))
            && (this.getTradepwdModifyTime() == null ? other.getTradepwdModifyTime() == null : this.getTradepwdModifyTime().equals(other.getTradepwdModifyTime()))
            && (this.getInvitationCode() == null ? other.getInvitationCode() == null : this.getInvitationCode().equals(other.getInvitationCode()))
            && (this.getChannelId() == null ? other.getChannelId() == null : this.getChannelId().equals(other.getChannelId()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getLoginTime() == null ? other.getLoginTime() == null : this.getLoginTime().equals(other.getLoginTime()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getLoginName() == null) ? 0 : getLoginName().hashCode());
        result = prime * result + ((getLoginNameEmail() == null) ? 0 : getLoginNameEmail().hashCode());
        result = prime * result + ((getLoginPwd() == null) ? 0 : getLoginPwd().hashCode());
        result = prime * result + ((getLoginpwdModifyTime() == null) ? 0 : getLoginpwdModifyTime().hashCode());
        result = prime * result + ((getRegistTime() == null) ? 0 : getRegistTime().hashCode());
        result = prime * result + ((getRegisterClient() == null) ? 0 : getRegisterClient().hashCode());
        result = prime * result + ((getTradePwd() == null) ? 0 : getTradePwd().hashCode());
        result = prime * result + ((getTradepwdModifyTime() == null) ? 0 : getTradepwdModifyTime().hashCode());
        result = prime * result + ((getInvitationCode() == null) ? 0 : getInvitationCode().hashCode());
        result = prime * result + ((getChannelId() == null) ? 0 : getChannelId().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getLoginTime() == null) ? 0 : getLoginTime().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        return result;
    }
}