package com.adpanshi.cashloan.manage.cl.model;

import java.io.Serializable;
import java.util.Date;

public class UserApps implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_apps_1.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_apps_1.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_apps_1.app_name
     *
     * @mbg.generated
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_apps_1.package_name
     *
     * @mbg.generated
     */
    private String packageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_apps_1.iexpress
     *
     * @mbg.generated
     */
    private Integer iexpress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_apps_1.system_type
     *
     * @mbg.generated
     */
    private Integer systemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_apps_1.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_apps_1.gmt_create_time
     *
     * @mbg.generated
     */
    private Date gmtCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_user_apps_1.remarks
     *
     * @mbg.generated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_user_apps_1
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_apps_1.id
     *
     * @return the value of cl_user_apps_1.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_apps_1.id
     *
     * @param id the value for cl_user_apps_1.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_apps_1.user_id
     *
     * @return the value of cl_user_apps_1.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_apps_1.user_id
     *
     * @param userId the value for cl_user_apps_1.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_apps_1.app_name
     *
     * @return the value of cl_user_apps_1.app_name
     *
     * @mbg.generated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_apps_1.app_name
     *
     * @param appName the value for cl_user_apps_1.app_name
     *
     * @mbg.generated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_apps_1.package_name
     *
     * @return the value of cl_user_apps_1.package_name
     *
     * @mbg.generated
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_apps_1.package_name
     *
     * @param packageName the value for cl_user_apps_1.package_name
     *
     * @mbg.generated
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName == null ? null : packageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_apps_1.iexpress
     *
     * @return the value of cl_user_apps_1.iexpress
     *
     * @mbg.generated
     */
    public Integer getIexpress() {
        return iexpress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_apps_1.iexpress
     *
     * @param iexpress the value for cl_user_apps_1.iexpress
     *
     * @mbg.generated
     */
    public void setIexpress(Integer iexpress) {
        this.iexpress = iexpress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_apps_1.system_type
     *
     * @return the value of cl_user_apps_1.system_type
     *
     * @mbg.generated
     */
    public Integer getSystemType() {
        return systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_apps_1.system_type
     *
     * @param systemType the value for cl_user_apps_1.system_type
     *
     * @mbg.generated
     */
    public void setSystemType(Integer systemType) {
        this.systemType = systemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_apps_1.state
     *
     * @return the value of cl_user_apps_1.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_apps_1.state
     *
     * @param state the value for cl_user_apps_1.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_apps_1.gmt_create_time
     *
     * @return the value of cl_user_apps_1.gmt_create_time
     *
     * @mbg.generated
     */
    public Date getGmtCreateTime() {
        return gmtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_apps_1.gmt_create_time
     *
     * @param gmtCreateTime the value for cl_user_apps_1.gmt_create_time
     *
     * @mbg.generated
     */
    public void setGmtCreateTime(Date gmtCreateTime) {
        this.gmtCreateTime = gmtCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_user_apps_1.remarks
     *
     * @return the value of cl_user_apps_1.remarks
     *
     * @mbg.generated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_user_apps_1.remarks
     *
     * @param remarks the value for cl_user_apps_1.remarks
     *
     * @mbg.generated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_apps_1
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserApps other = (UserApps) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getAppName() == null ? other.getAppName() == null : this.getAppName().equals(other.getAppName()))
            && (this.getPackageName() == null ? other.getPackageName() == null : this.getPackageName().equals(other.getPackageName()))
            && (this.getIexpress() == null ? other.getIexpress() == null : this.getIexpress().equals(other.getIexpress()))
            && (this.getSystemType() == null ? other.getSystemType() == null : this.getSystemType().equals(other.getSystemType()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getGmtCreateTime() == null ? other.getGmtCreateTime() == null : this.getGmtCreateTime().equals(other.getGmtCreateTime()))
            && (this.getRemarks() == null ? other.getRemarks() == null : this.getRemarks().equals(other.getRemarks()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_user_apps_1
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getAppName() == null) ? 0 : getAppName().hashCode());
        result = prime * result + ((getPackageName() == null) ? 0 : getPackageName().hashCode());
        result = prime * result + ((getIexpress() == null) ? 0 : getIexpress().hashCode());
        result = prime * result + ((getSystemType() == null) ? 0 : getSystemType().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getGmtCreateTime() == null) ? 0 : getGmtCreateTime().hashCode());
        result = prime * result + ((getRemarks() == null) ? 0 : getRemarks().hashCode());
        return result;
    }
}