package com.adpanshi.cashloan.manage.arc.mapper;


import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.arc.model.ArcLog;
import com.adpanshi.cashloan.manage.arc.model.ArcLogExample;
import com.adpanshi.cashloan.manage.arc.model.ArcLogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface ArcLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_log
     *
     * @mbg.generated
     */
    long countByExample(ArcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_log
     *
     * @mbg.generated
     */
    int deleteByExample(ArcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_log
     *
     * @mbg.generated
     */
    int insert(ArcLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_log
     *
     * @mbg.generated
     */
    int insertSelective(ArcLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_log
     *
     * @mbg.generated
     */
    List<ArcLogWithBLOBs> selectByExampleWithBLOBs(ArcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_log
     *
     * @mbg.generated
     */
    List<ArcLog> selectByExample(ArcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_log
     *
     * @mbg.generated
     */
    ArcLogWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ArcLogWithBLOBs record, @Param("example") ArcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ArcLogWithBLOBs record, @Param("example") ArcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ArcLog record, @Param("example") ArcLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ArcLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ArcLogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ArcLog record);
}