package com.adpanshi.cashloan.manage.arc.mapper;

import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.arc.model.Credit;
import com.adpanshi.cashloan.manage.arc.model.CreditExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface CreditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_credit
     *
     * @mbg.generated
     */
    long countByExample(CreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_credit
     *
     * @mbg.generated
     */
    int deleteByExample(CreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_credit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_credit
     *
     * @mbg.generated
     */
    int insert(Credit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_credit
     *
     * @mbg.generated
     */
    int insertSelective(Credit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_credit
     *
     * @mbg.generated
     */
    List<Credit> selectByExample(CreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_credit
     *
     * @mbg.generated
     */
    Credit selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_credit
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Credit record, @Param("example") CreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_credit
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Credit record, @Param("example") CreditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_credit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Credit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_credit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Credit record);
}