package com.adpanshi.cashloan.manage.arc.mapper;


import com.adpanshi.cashloan.common.mapper.RDBatisDao;
import com.adpanshi.cashloan.manage.arc.model.SysDictDetail;
import com.adpanshi.cashloan.manage.arc.model.SysDictDetailExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;
@RDBatisDao
public interface SysDictDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_sys_dict_detail
     *
     * @mbg.generated
     */
    long countByExample(SysDictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_sys_dict_detail
     *
     * @mbg.generated
     */
    int deleteByExample(SysDictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_sys_dict_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_sys_dict_detail
     *
     * @mbg.generated
     */
    int insert(SysDictDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_sys_dict_detail
     *
     * @mbg.generated
     */
    int insertSelective(SysDictDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_sys_dict_detail
     *
     * @mbg.generated
     */
    List<SysDictDetail> selectByExample(SysDictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_sys_dict_detail
     *
     * @mbg.generated
     */
    SysDictDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_sys_dict_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysDictDetail record, @Param("example") SysDictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_sys_dict_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysDictDetail record, @Param("example") SysDictDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_sys_dict_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysDictDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table arc_sys_dict_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysDictDetail record);

    /**
     * 新增时查询额度类型名称
     * @param data
     * @return
     */
    List<SysDictDetail> listByTypeCode(Map<String, Object> data);
}